services:
  web:
    image: nginx:alpine
    container_name: webholeink_org_web
    restart: unless-stopped
    volumes:
      - ./:/var/www/webholeink:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    depends_on:
      - app

  app:
    image: php:8.3-fpm-alpine
    container_name: webholeink_org_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/webholeink
    networks:
      - web

networks:
  web:
    external: true
